#!/usr/bin/env python3

from rog.device import DeviceMeta

UDEV_RULES = '/etc/udev/rules.d/50-rogdrv.rules'


def main():
    rules = ['KERNEL=="uinput", MODE="0666"']

    matches = (
        'SUBSYSTEM=="hidraw"',
        'KERNEL=="hidraw*"',
    )

    for c in DeviceMeta.device_classes:
        rules.append(', '.join(matches + (
            'ATTRS{{idVendor}}=="{:04x}"'.format(c.vendor_id),
            'ATTRS{{idProduct}}=="{:04x}"'.format(c.product_id),
            'MODE="0666"',
        )))

        rules.append(', '.join(matches + (
            'KERNELS=="0003:{:04x}:{:04x}.*"'.format(c.vendor_id, c.product_id),
            'MODE="0666"',
        )))

    with open(UDEV_RULES, 'w') as f:
        for rule in rules:
            f.write(rule + '\n')

    print('udev rules are saved into "{}"'.format(UDEV_RULES))
    print('run to apply them:')
    print('$ sudo udevadm control --reload-rules')
    print('$ sudo udevadm trigger')


if __name__ == '__main__':
    main()
