#!/usr/bin/env python3

# Copyright (C) 2018 Kyoken, kyoken@kyoken.ninja

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3
# of the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

import sys

from rog.device import Pugio


def main():
    if len(sys.argv) >= 2:
        if sys.argv[1] == 'bind':
            device = Pugio()
            if len(sys.argv) >= 4:
                slot = int(sys.argv[2])
                button = sys.argv[3].lower()
                if button.startswith('0x'):
                    button = int(button, 16)
                else:
                    button = int(button)
                device.bind(slot, button)

            print(device.get_bindings())
            return

        elif sys.argv[1] == 'color':
            device = Pugio()
            if len(sys.argv) >= 6:
                slot = int(sys.argv[2])
                r = int(sys.argv[3])
                g = int(sys.argv[4])
                b = int(sys.argv[5])
                device.set_color(slot, (r, g, b))

            print(device.get_colors())
            return

    device = Pugio()
    while True:
        e = device.next_event()
        device.handle_event(e)


if __name__ == '__main__':
    main()
